spring:
  application:
    name: Shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Shop
    username: root
    password: root
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql : true
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: accthanh001@gmail.com
    password: "mmzx mdeu rplt epeo"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  spring.mail.properties.mail.smtp.auth: true




green:
  jwt:
    expiration: ${GREEN_JWT_EXPIRATION:600000}
    secretKey: ${GREEN_JWT_SECRET_KEY:GREENACADEMY_SECRET_KEY}



server:
  port: 8282